In [ ]:
#| hide
from archette import GARCHETTE

# archette

> tiny arch model

GARCHETTE is a minimal implementation of the GARCH(1,1) model with zero mean and Gaussian noise.

## Usage

### Installation

Install latest from the GitHub [repository][repo]:

```sh
$ pip install git+https://github.com/xiaochuany/archette.git
```

[repo]: https://github.com/xiaochuany/archette
[docs]: https://xiaochuany.github.io/archette/

### Documentation

Documentation can be found hosted on this GitHub [repository][repo]'s [pages][docs].

[repo]: https://github.com/xiaochuany/archette
[docs]: https://xiaochuany.github.io/archette/
[pypi]: https://pypi.org/project/archette/
[conda]: https://anaconda.org/xiaochuany/archette

## How to use

In [ ]:
import numpy as np
from archette import GARCHETTE

In [ ]:
y = np.random.randn(20)
mod = GARCHETTE()
mod.fit(y)

<archette.core.GARCHETTE>

One can get inspect the fit params: a triplet of omega, alpha and beta as in 

$$
\begin{align*}
Y_t &= \sigma_t W_t \\
\sigma_t^2 &=  \omega + \alpha Y_{t-1}^2 + \beta \sigma^2_{t-1} 
\end{align*}
$$

In [ ]:
mod.params

array([0.41124553, 0.        , 0.31705585])

The conditional variance of the fit model is computed by the recursion
$$
\begin{equation}
\hat{\sigma}_t^2 = \hat{\omega} + \hat{\alpha} + \hat{\beta} \hat{\sigma}_{t-1}^2
\end{equation}
$$
which depends entirely on the unobserved $\sigma_0^2$. 
The model sets a sensible default value for it. 



In [ ]:
mod.vs

array([0.60808129, 0.60404127, 0.60276035, 0.60235423, 0.60222547,
       0.60218464, 0.6021717 , 0.60216759, 0.60216629, 0.60216588,
       0.60216575, 0.60216571, 0.60216569, 0.60216569, 0.60216569,
       0.60216569, 0.60216569, 0.60216569, 0.60216569, 0.60216569])

The standardised residual is deduced from the conditional variance 
$$
\begin{equation}
r_t = \frac{y_t}{\hat{\sigma}_t}
\end{equation}
$$

In [ ]:
mod.std_resids

array([-1.17812072, -0.99035699, -0.22087847,  0.38903965, -1.19532934,
       -0.14457363, -1.43213792,  1.72189974, -0.41315769, -0.11995525,
        2.35278337,  0.22319601, -0.3727941 ,  1.56851779, -0.34142197,
        0.43569726, -0.89645315,  0.58623321,  1.10074337,  0.15922077])

Finally, one can forecast the condtional variance and simulate the process with the fit parameters with a given horizon 

In [ ]:
mod.forecast_vs(horizon=5)

array([0.60216569, 0.60216569, 0.60216569, 0.60216569, 0.60216569])

In [ ]:
mod.simulate(horizon=5, method="bootstrap", n_rep=2, seed=1)

array([[-0.11218818,  0.17319862, -0.28928574, -0.32060762, -0.09308448],
       [ 0.17319862, -0.11218818,  0.33809818, -0.91421385, -0.69564168]])