In [1]:
#| hide
from archette import GARCHETTE

# archette

> tiny arch model

This file will become your README and also the index of your documentation.

## Usage

### Installation

Install latest from the GitHub [repository][repo]:

```sh
$ pip install git+https://github.com/xiaochuany/archette.git
```

[repo]: https://github.com/xiaochuany/archette
[docs]: https://xiaochuany.github.io/archette/

### Documentation

Documentation can be found hosted on this GitHub [repository][repo]'s [pages][docs].

[repo]: https://github.com/xiaochuany/archette
[docs]: https://xiaochuany.github.io/archette/
[pypi]: https://pypi.org/project/archette/
[conda]: https://anaconda.org/xiaochuany/archette

## How to use

GARCHETTE is a minimal implementation of the GARCH(1,1) model with zero mean and t noise distribution.  

In [2]:
import numpy as np

In [3]:
y = np.random.randn(20)
mod = GARCHETTE()
mod.fit(y)

One can get inspect the fit params: a triplet of omega, alpha and beta as in 

$$
\begin{align*}
Y_t &= \sigma_t W_t \\
\sigma_t^2 &=  \omega + \alpha Y_{t-1}^2 + \beta \sigma^2_{t-1} 
\end{align*}
$$

In [4]:
mod.params

array([5.35044290e-01, 5.51887136e-17, 7.46091855e-01])

The conditional variance of the fit model is computed by the recursion
$$
\hat{\sigma}_t^2 = \hat{\omega} + \hat{\alpha} + \hat{\beta} \hat{\sigma}_{t-1}^2
$$
which depends entirely on the unobserved $\sigma_0^2$. 
The model sets a sensible default value for it. 



In [5]:
mod.vs

array([1.29046242, 1.49784779, 1.65257633, 1.76801803, 1.85414814,
       1.91840912, 1.96635371, 2.00212478, 2.02881328, 2.04872535,
       2.06358159, 2.07466571, 2.08293548, 2.08910549, 2.09370888,
       2.09714343, 2.09970592, 2.10161778, 2.1030442 , 2.10410844])

The standardised residual is deduced from the conditional variance 
$$
r_t = \frac{y_t}{\hat{\sigma}_t}
$$

In [6]:
mod.std_resids

array([-0.47799613, -0.27976356,  0.5103788 , -0.0533626 ,  1.4564594 ,
        0.22381068, -0.17513649, -0.79248877,  0.05083456,  1.06545824,
        1.80403929,  0.19133979, -1.02151068, -0.01529507,  0.66761498,
       -0.90275061, -0.27395279,  0.07464924, -0.04860764, -0.22528522])

Finally, one can forecast the condtional variance and simulate the process with the fit parameters with a given horizon 

In [7]:
mod.forecast_vs(horizon=5)

array([2.10490246, 2.10549487, 2.10593686, 2.10626663, 2.10651267])

In [8]:
mod.simulate(horizon=5, method="bootstrap", n_rep=2, seed=1)

array([[ 0.32471085,  0.27764022, -1.4824006 ,  0.07377611,  1.546388  ],
       [ 0.27760116,  0.32475654, -1.31005783, -0.69371495, -0.39761043]])