In [ ]:
#| hide
from archette import GARCHETTE

# archette

> tiny arch model

GARCHETTE is a minimal implementation of the GARCH(1,1) model with zero mean and t noise distribution.  

## Usage

### Installation

Install latest from the GitHub [repository][repo]:

```sh
$ pip install git+https://github.com/xiaochuany/archette.git
```

[repo]: https://github.com/xiaochuany/archette
[docs]: https://xiaochuany.github.io/archette/

### Documentation

Documentation can be found hosted on this GitHub [repository][repo]'s [pages][docs].

[repo]: https://github.com/xiaochuany/archette
[docs]: https://xiaochuany.github.io/archette/
[pypi]: https://pypi.org/project/archette/
[conda]: https://anaconda.org/xiaochuany/archette

## How to use

In [ ]:
import numpy as np
from archette import GARCHETTE

In [ ]:
y = np.random.randn(20)
mod = GARCHETTE()
mod.fit(y)

<archette.core.GARCHETTE>

One can get inspect the fit params: a triplet of omega, alpha and beta as in 

$$
\begin{align*}
Y_t &= \sigma_t W_t \\
\sigma_t^2 &=  \omega + \alpha Y_{t-1}^2 + \beta \sigma^2_{t-1} 
\end{align*}
$$

In [ ]:
mod.params

array([1.04589446e-08, 0.00000000e+00, 9.59108222e-01])

The conditional variance of the fit model is computed by the recursion
$$
\hat{\sigma}_t^2 = \hat{\omega} + \hat{\alpha} + \hat{\beta} \hat{\sigma}_{t-1}^2
$$
which depends entirely on the unobserved $\sigma_0^2$. 
The model sets a sensible default value for it. 



In [ ]:
mod.vs

array([1.16724226, 1.11951166, 1.07373285, 1.02982602, 0.98771461,
       0.94732521, 0.90858741, 0.87143367, 0.83579921, 0.8016219 ,
       0.76884217, 0.73740285, 0.70724915, 0.67832849, 0.65059044,
       0.62398665, 0.59847074, 0.57399821, 0.55052642, 0.52801442])

The standardised residual is deduced from the conditional variance 
$$
r_t = \frac{y_t}{\hat{\sigma}_t}
$$

In [ ]:
mod.std_resids

array([-1.48253982, -1.39672222,  0.46659989,  0.18568779, -0.46756732,
        0.88546338, -2.78458467,  1.23434105,  0.21509406, -1.72585335,
       -0.1004795 ,  0.9924512 ,  0.80529043, -0.12976872,  0.89918346,
        1.18351147,  1.44555856,  0.07340447,  0.50764082,  0.51763172])

Finally, one can forecast the condtional variance and simulate the process with the fit parameters with a given horizon 

In [ ]:
mod.forecast_vs(horizon=5)

array([0.50642299, 0.48571446, 0.46585274, 0.44680321, 0.42853264])

In [ ]:
mod.simulate(horizon=5, method="bootstrap", n_rep=2, seed=1)

array([[ 0.63012587,  0.69167118,  0.54963815,  0.14377605, -1.1297851 ],
       [ 0.70626204,  0.61710792,  0.80778689, -0.99097913,  0.94629739]])