In [ ]:
#| hide
from archette import GARCHETTE

# archette

> tiny arch model

GARCHETTE is a minimal implementation of the GARCH(1,1) model with zero mean and Gaussian noise.

## Usage

### Installation

Install latest from the GitHub [repository][repo]:

```sh
$ pip install git+https://github.com/xiaochuany/archette.git
```

[repo]: https://github.com/xiaochuany/archette
[docs]: https://xiaochuany.github.io/archette/

### Documentation

Documentation can be found hosted on this GitHub [repository][repo]'s [pages][docs].

[repo]: https://github.com/xiaochuany/archette
[docs]: https://xiaochuany.github.io/archette/
[pypi]: https://pypi.org/project/archette/
[conda]: https://anaconda.org/xiaochuany/archette

## How to use

In [ ]:
import numpy as np
from archette import GARCHETTE

In [ ]:
y = np.random.randn(20)
mod = GARCHETTE()
mod.fit(y)

<archette.core.GARCHETTE>

One can get inspect the fit params: a triplet of omega, alpha and beta as in 

$$
\begin{align*}
Y_t &= \sigma_t W_t \\
\sigma_t^2 &=  \omega + \alpha Y_{t-1}^2 + \beta \sigma^2_{t-1} 
\end{align*}
$$

In [ ]:
mod.params

array([3.53477729e-03, 1.16474111e-12, 9.99999999e-01])

The conditional variance of the fit model is computed by the recursion

$$
\begin{equation}
\hat{\sigma}_t^2 = \hat{\omega} + \hat{\alpha} + \hat{\beta} \hat{\sigma}_{t-1}^2
\end{equation}
$$

which depends entirely on the unobserved $\sigma_0^2$. 
The model sets a sensible default value for it. 



In [ ]:
mod.vs

array([0.87484097, 0.87837574, 0.88191052, 0.8854453 , 0.88898007,
       0.89251485, 0.89604963, 0.8995844 , 0.90311918, 0.90665395,
       0.91018873, 0.91372351, 0.91725828, 0.92079306, 0.92432784,
       0.92786261, 0.93139739, 0.93493217, 0.93846694, 0.94200172])

The standardised residual is deduced from the conditional variance 

$$
r_t = \frac{y_t}{\hat{\sigma}_t}
$$

In [ ]:
mod.std_resids

array([ 0.62885304,  0.92687193, -0.74230796,  1.89461301,  0.14705346,
       -0.2527923 ,  0.99041857,  0.67073369,  1.2168398 ,  0.89108207,
       -1.63655212, -0.69107348, -0.51659492, -1.21672958,  0.78484646,
       -0.24441403, -1.20978739, -0.72337278, -0.75813741,  1.50086911])

Finally, one can forecast the condtional variance and simulate the process with the fit parameters with a given horizon 

In [ ]:
mod.forecast_vs(horizon=5)

array([0.9455365 , 0.94907127, 0.95260605, 0.95614083, 0.9596756 ])

In [ ]:
mod.simulate(horizon=5, method="bootstrap", n_rep=2, seed=1)

array([[-0.24581195, -0.67324578, -0.50420459,  1.18985581,  0.87293103],
       [-0.67199087, -0.24627099, -0.23855186,  0.61490793, -1.18514443]])